
// Earth radius in meters
export const EARTH_RADIUS = 6378137;

// OpenStreetMap Tiles (Standard) - We will invert these with CSS for Dark Mode with visible text
export const TILE_LAYER_URL = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
export const TILE_ATTRIBUTION = '&copy; <a href="https://www.openstreetmap.org/copyright">OSM</a>';

// Default Start (Moscow Red Square roughly, if Geo fails)
export const DEFAULT_CENTER = { lat: 55.7539, lng: 37.6208 };

// Step Length (Average in meters)
export const STEP_LENGTH = 0.76;

// Sensor Thresholds
export const MOTION_THRESHOLD = 1.2; // G-force variance to count a step

export const TRANSLATIONS = {
  RU: {
    dist: 'Дистанция',
    azimuth: 'Азимут',
    steps: 'ШАГИ',
    target: 'Цель',
    notSet: 'НЕ ЗАДАНА',
    allowSensors: 'РАЗРЕШИТЬ ДАТЧИКИ',
    start: 'ПОЕХАЛИ',
    correct: 'Я ЗДЕСЬ',
    stop: 'СТОП',
    return: 'НАЗАД',
    finished: 'Маршрут завершен',
    newRoute: 'НОВЫЙ МАРШРУТ',
    correctionTitle: 'Коррекция Позиции',
    correctionDesc: 'Наведите центр карты или введите адрес.',
    placeholderAddr: 'Введите адрес...',
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    searchFrom: 'ОТКУДА (Текущая позиция)',
    searchTo: 'КУДА (Адрес финиша)',
    searchBtn: 'ПОИСК...',
    routeBtn: 'ПОСТРОИТЬ МАРШРУТ',
    planRouteHeader: 'ПЛАНИРОВАНИЕ',
    pickA: 'Нажмите на карту, чтобы выбрать точку А',
    pickB: 'Нажмите на карту, чтобы выбрать точку Б',
    pickCorrect: 'Наведите центр на точку',
    pickOnMapBtn: 'УКАЗАТЬ НА КАРТЕ',
    tapMapHint: 'НАЖМИТЕ НА КАРТУ ДЛЯ ВЫБОРА',
    stopConfirmTitle: 'ЗАВЕРШИТЬ?',
    stopConfirmDesc: 'Завершить или вернуться по следам?',
    yes: 'ЗАВЕРШИТЬ',
    no: 'ОТМЕНА',
    gpsOn: 'GPS: ВКЛ',
    gpsOff: 'GPS: ВЫКЛ',
    geoError: 'Не удалось найти точку назначения',
    correctionError: 'Не удалось найти адрес для коррекции',
    byAuthor: 'BY DZHEITYUK',
    imHere: 'Я ТУТ',
    toHere: 'СЮДА',
    hereBtn: 'ТУТ',
    byAddress: 'ПО АДРЕСУ',
    backToMap: 'НА КАРТУ',
    calib: 'ЗАФИКСИРОВАТЬ КУРС',
    unlock: 'РАЗБЛОКИРОВАТЬ',
    resetPath: 'СБРОС ПУТИ',
    stepLen: 'ДЛИНА ШАГА (м)',
    help: 'ИНСТРУКЦИЯ',
    helpTitle: 'GIROMAP (GIROMAP.RU)',
    supportBtn: 'ПОМОЩЬ ПРОЕКТУ',
    helpText: [
      'GiroMap — навигация методом счисления пути (Dead Reckoning).',
      '• ПОИСК (Лупа): Выбор точек А и Б. ИИ DeepSeek выдает краткую справку о месте назначения.',
      '• КУРС (Джойстик): Вращайте карту, чтобы совместить линию маршрута с направлением вашего взгляда («вверх»).',
      '• ФИКСАЦИЯ (Lock): Кнопка «ЗАФИКСИРОВАТЬ КУРС» замораживает карту. Устройство превращается в стабильный гирокомпас.',
      '• ДВИЖЕНИЕ: Просто идите. Акселерометр считает шаги и перемещает вас по линии маршрута без участия GPS.',
      '• КОРРЕКЦИЯ (Я ЗДЕСЬ): Если позиция сбилась, нажмите «Я ЗДЕСЬ» -> «ТУТ», наведя перекрестие на ваше реальное положение.',
      '• ДЛИНА ШАГА: В режиме коррекции можно настроить длину шага (м) для более точного перемещения под ваш темп.',
      '• GPS: Используется только для начальной привязки или экстренной проверки (кнопка в углу).',
      '• ТУТ/СЮДА: Быстрое назначение старта или финиша по центру экрана в режиме планирования.',
      '• СБРОС ПУТИ: Очищает серый след пройденного вами пути.',
      '• iOS: Для корректного доступа к датчикам используйте Safari -> «Поделиться» -> «На экран Домой».'
    ]
  },
  EN: {
    dist: 'Distance',
    azimuth: 'Azimuth',
    steps: 'STEPS',
    target: 'Target',
    notSet: 'NOT SET',
    allowSensors: 'ALLOW SENSORS',
    start: 'LET\'S GO',
    correct: 'I AM HERE',
    stop: 'STOP',
    return: 'RETURN',
    finished: 'Route Finished',
    newRoute: 'NEW ROUTE',
    correctionTitle: 'Position Correction',
    correctionDesc: 'Aim map center or enter address.',
    placeholderAddr: 'Enter address...',
    cancel: 'Cancel',
    confirm: 'Confirm',
    searchFrom: 'FROM (Current Loc)',
    searchTo: 'TO (Destination)',
    searchBtn: 'SEARCHING...',
    routeBtn: 'BUILD ROUTE',
    planRouteHeader: 'PLAN ROUTE',
    pickA: 'Tap map to pick Point A',
    pickB: 'Tap map to pick Point B',
    pickCorrect: 'Aim center at location',
    pickOnMapBtn: 'PICK ON MAP',
    tapMapHint: 'TAP MAP TO SELECT LOCATION',
    stopConfirmTitle: 'FINISH ROUTE?',
    stopConfirmDesc: 'Finish or Backtrack?',
    yes: 'FINISH',
    no: 'CANCEL',
    gpsOn: 'GPS: ON',
    gpsOff: 'GPS: OFF',
    geoError: 'Failed to find destination',
    correctionError: 'Failed to find correction address',
    byAuthor: 'BY DZHEITYUK',
    imHere: 'I\'M HERE',
    toHere: 'TO HERE',
    hereBtn: 'HERE',
    byAddress: 'BY ADDRESS',
    backToMap: 'BACK TO MAP',
    calib: 'LOCK COURSE',
    unlock: 'UNLOCK MAP',
    resetPath: 'RESET PATH',
    stepLen: 'STEP LENGTH (m)',
    help: 'HELP',
    helpTitle: 'GIROMAP (GIROMAP.RU)',
    supportBtn: 'SUPPORT PROJECT',
    helpText: [
      'GiroMap — Dead Reckoning pedestrian navigation.',
      '• SEARCH (Magnifier): Pick points A and B. DeepSeek AI provides a short fact about your destination.',
      '• COURSE (Joystick): Rotate the map to align the route line vertically (pointing "forward").',
      '• LOCK: "LOCK COURSE" freezes map rotation. Your device now acts as a stable gyroscopic guide.',
      '• MOVEMENT: Just walk forward. Accelerometer counts steps and moves you along the path without GPS.',
      '• CORRECTION (I\'M HERE): If you drift, use "HERE" button while aiming the center at your real spot.',
      '• STEP LENGTH: Adjust your step size (m) in correction mode for better movement accuracy.',
      '• GPS: Use it for initial calibration or emergency location sync (corner button).',
      '• HERE/TO HERE: Quick set start/finish based on the current screen center.',
      '• RESET PATH: Clears the trail of your walked movement.',
      '• iOS: For sensor access, use Safari -> "Share" -> "Add to Home Screen".'
    ]
  }
};
